# Generated by Django 3.1 on 2021-05-24 18:10

from django.db import migrations, models
import django.db.models.deletion
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age_preference', inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True)),
                ('role', models.CharField(max_length=256, null=True)),
                ('job_title', models.CharField(max_length=256, null=True)),
                ('keyword', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=256, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('salary_range', inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True)),
                ('vacant_position', models.CharField(max_length=256, null=True)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')], default=True)),
                ('months_of_experience', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('gender_preference', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ANY', 'Any')], default=True, max_length=6)),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('summary', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')], default=True)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Single')], default=True)),
                ('phone', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('birthday', models.DateField(null=True)),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('summary', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('phone_code', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=256, null=True)),
                ('founding_date', models.DateField(null=True)),
                ('website', models.CharField(max_length=256, null=True)),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, null=True)),
                ('question', models.CharField(max_length=256, null=True)),
                ('answer', models.JSONField(null=True)),
                ('time', models.TimeField(null=True)),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, null=True)),
                ('end', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.organization', to_field='email')),
                ('participants', models.ManyToManyField(to='myapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=256, null=True)),
                ('linkedin', models.CharField(max_length=256, null=True)),
                ('twitter', models.CharField(max_length=256, null=True)),
                ('instagram', models.CharField(max_length=256, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.organization', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.test'),
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LO', 'Low'), ('ML', 'Mid-low'), ('MI', 'Middle'), ('MH', 'Mid-high'), ('HI', 'High')], default='LO', max_length=2)),
                ('name', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(max_length=256, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.application')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=256, null=True)),
                ('summary', models.CharField(max_length=256, null=True)),
                ('start_date', models.DateField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('salary_rate', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=1)),
                ('curruncy', models.CharField(max_length=256, null=True)),
                ('job_title', models.CharField(max_length=256, null=True)),
                ('company', models.CharField(max_length=256, null=True)),
                ('months_of_experience', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LO', "Bachelor's degree"), ('ML', "Master's degree"), ('MI', 'Doctoral degree')], default='LO', max_length=2)),
                ('graduation_status', models.BooleanField(choices=[(True, 'Graduated'), (False, 'Not graduated')], default=True, null=True)),
                ('major', models.CharField(max_length=256, null=True)),
                ('university', models.CharField(max_length=256, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.application')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('issuing_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('institute', models.CharField(max_length=256, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')], default=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.organization')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.organization', to_field='email'),
        ),
    ]
