# Generated by Django 3.0.6 on 2021-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_date',
            field=models.DateField(auto_now=True),
        ),
    ]
