# Generated by Django 3.1 on 2021-05-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.question')),
            ],
        ),
    ]
