# Generated by Django 3.0.6 on 2021-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_user_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
