# Generated by Django 3.1 on 2021-05-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210526_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
