# Generated by Django 3.1 on 2021-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210526_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='participants',
            field=models.ManyToManyField(null=True, to='myapi.Employee'),
        ),
    ]
