# Generated by Django 3.0.6 on 2021-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210404_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_date',
        ),
    ]
