# Generated by Django 3.0.6 on 2021-04-20 15:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_user_signup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('languages', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')], default=True)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Single')], default=True)),
                ('phone', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=256)),
                ('cv', models.FileField(upload_to='')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('birthday', models.DateField()),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LO', 'Low'), ('ML', 'Mid-low'), ('MI', 'Middle'), ('MH', 'Mid-high'), ('HI', 'High')], max_length=2)),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
