# Generated by Django 3.0.6 on 2021-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_user_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='one', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='one', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='one', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(default='one', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='one', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='employment',
            field=models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default='one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.FileField(default='one', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(default='one', max_length=256),
            preserve_default=False,
        ),
    ]
