# Generated by Django 3.0.6 on 2021-04-24 15:06

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210420_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('salary', models.IntegerField()),
                ('salary_rate', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1)),
                ('curruncy', models.CharField(max_length=256)),
                ('job_title', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('months_of_experience', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LO', "Bachelor's degree"), ('ML', "Master's degree"), ('MI', 'Doctoral degree')], max_length=2)),
                ('graduation_status', models.BooleanField(choices=[(True, 'Graduated'), (False, 'Not graduated')], default=True)),
                ('major', models.CharField(max_length=256)),
                ('university', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('issuing_date', models.DateField()),
                ('description', models.CharField(max_length=256)),
                ('institute', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Employee')),
            ],
        ),
    ]
