# Generated by Django 3.0.6 on 2021-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210405_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=256),
        ),
    ]
