# Generated by Django 3.0.6 on 2021-04-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_courses_education_experiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone_code', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('founding_date', models.DateField()),
                ('website', models.CharField(max_length=256)),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=256)),
                ('linkedin', models.CharField(max_length=256)),
                ('twitter', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Organization')),
            ],
        ),
    ]
