# Generated by Django 3.0.6 on 2021-04-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_organization_sociallink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='ProfessionalSkills',
            new_name='ProfessionalSkill',
        ),
    ]
