# Generated by Django 3.1 on 2021-04-29 07:26

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210427_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee'),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('end', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organization')),
                ('participants', models.ManyToManyField(to='myapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('question', models.CharField(max_length=256)),
                ('answer', models.JSONField()),
                ('time', models.TimeField()),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.test')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age_preference', inclusive_django_range_fields.fields.InclusiveIntegerRangeField()),
                ('role', models.CharField(max_length=256)),
                ('job_title', models.CharField(max_length=256)),
                ('keyword', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('salary_range', inclusive_django_range_fields.fields.InclusiveIntegerRangeField()),
                ('vacant_position', models.CharField(max_length=256)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')], default=True)),
                ('languages', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('months_of_experience', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.CharField(max_length=256)),
                ('gender_preference', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ANY', 'Any')], max_length=6)),
                ('employment', models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organization')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.application'),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.application'),
        ),
    ]
