# Generated by Django 3.1 on 2021-05-23 16:40

from django.db import migrations, models
import django_countries.fields
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210505_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age_preference',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary_range',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment',
            field=models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='summary',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employment',
            field=models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founding_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='summary',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='facebook',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='instagram',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedin',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='twitter',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
