# Generated by Django 3.1 on 2021-05-23 16:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20210523_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment',
            field=models.CharField(choices=[('FU', 'Full time'), ('PA', 'Part time'), ('FR', 'Freelance'), ('VO', 'Volunteering'), ('TR', 'Training'), ('FL', 'Flexible work')], default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender_preference',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ANY', 'Any')], default=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='keyword',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='months_of_experience',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='vacant_position',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='issuing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('LO', "Bachelor's degree"), ('ML', "Master's degree"), ('MI', 'Doctoral degree')], default='LO', max_length=2),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='curruncy',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.employee'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='industry_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='months_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary_rate',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='level',
            field=models.CharField(choices=[('LO', 'Low'), ('ML', 'Mid-low'), ('MI', 'Middle'), ('MH', 'Mid-high'), ('HI', 'High')], default='LO', max_length=2),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
